title: '0xBlackmida.github.io'
description: "Tech hub"
baseurl: "/"
url: "https://0xBlackmida.github.io"

header_pages:
  - index.md
  - h4ck.md
  #- about.md
  #- contact.md

style: dark

footer: '<a href="https://x.com/">X</a> | <a href="https://github.com/">GitHub</a> | <a href="https://mirror.xyz/">Mirror</a>'

# Build settings
markdown: kramdown
#remote_theme: b2a3e8/jekyll-theme-console
